### ISSUE TITLE
Administracia - Navigacia - upravit stylovanie podla stavu daneho odkazu

### ISSUE THREAD

**Issue by tomasSlouka** [tomasSlouka/test#10]
Stav daneho odkazu znamena, ze ak je napriklad neviditelny tak aby cely text aj s ikonkami bol zosednuty. Zaroven trocha upravit prehladnost administracie navigacie aby bolo viac viditelne, ktore odkazy su hlavicky, ktore su odkazy a tiez odlisit odkazy, ktore su v podkategoriach.

**Comment by iBeaver** [comment]
Info: k stavu kedy bude link zasednuty a nebude mozne nanho kliknut aj s danym cursorom som vytvoril classu s nazvom .disable-button

**Comment by tomasSlouka** [comment]
chyba implementacia http://localhost/test/web/admin/navigation/o-obci | ludove umenie ;)
