### ISSUE TITLE
Administracia - Natiahnutie #page_wrapperu na 100% + overflow

### ISSUE THREAD

**Issue by tomasSlouka** [tomasSlouka/test#12]
Zas to nejde a ked sa to uz bude uz fixovat tak treba nastavit owerflowtovanie, tak aby tam nahodilo scrollbar

**Comment by iBeaver** [comment]
S overflow na scroll su urcite problemy pri responzivnej verzii, v niektorych pripadoch nefunguje, zistim preco a ako to opravit.

**Comment by tomasSlouka** [comment]
overfloatovanie by bolo aktivne len pri desktopoch. Na ostatnych zariadeniach nie je ani 100% vyska potrebna ked sa to tak vazme.

**Comment by tomasSlouka** [comment]
Tato uloha uz bola vyriesena nasadenim templatu 2 pre administraciu. Ulohu uzatvaram.
