### ISSUE TITLE
Kurzor pri tvorbe menu

### ISSUE THREAD

**Issue by iBeaver** [tomasSlouka/test#22]
Je nutné sa pohrať s kurzorom pri tvorbe menu, aby užívateľ vedel že prechádza cez "link" a može panel rozkliknúť je nutný kurzor ukazováka, ak prechádza nad ikonkami je nutný kurzor šípky.

**Comment by tomasSlouka** [comment]
Staci ak sa prida hover, tak aby sa vzdy rozsvietila aktivna oblast.
